### PR TITLE
Reflect Raku rename

### PR DESCRIPTION
**Pull request by sumanstats**
As the language is renamed to Raku and this is the most complete package that supports Raku, it is better to inherit that here.

This PR is to reflect that and I have made following changes:

+ change scope name of grammars file
+ rename of grammars file
+ rename spec file
+ add filetypes rakumod rakutest rakudoc
+ arrange filetypes based on priority, old extensions will be deprecated
  anyway
+ change name from Perl 6 --> Raku in raku.cson
+ change description in package.json to The Raku Programming Language
  Highlighter
+ edit contributing.md, change extensions of escape and unescape files
+ rename lp6iym.p6 to lriym.raku

### CODE REVIEW

**Comment by hankache** [comment]
Shouldn't we move this package to the `Raku` org?

**Review by JJ — APPROVED** [review]
It looks fine, and sorry about the delay.

**Comment by JJ** [comment]
@hankache we probably should.

**Comment by lizmat** [comment]
I understand Naoum Hankache lived close enough to the Beirut blast to have family members in hospital.  I suspect Naoum has different things on his mind now.

**Pull request merged**
